### PR TITLE
Updates for Cullenect v2

### PR DESCRIPTION
**Pull request by ndevenish**
see: https://github.com/ndevenish/gflabel/issues/7

Incomplete list of changes/TODO:

- Renamed `webb` base to `cullenect`. "`webb`" is still accepted, but not shown in the base type list
- Base type is now always required, to make gflabel more system-agnostic.
- Base type accepts partial base names, as long as it is an unambiguous prefix.
- Added `--version` for specifying base model versions, defaulting to `latest`. Currently only the Cullenect base has multiple versions, which are `latest`, `v1.1` (same as `latest`), and `v2.0.3-beta`. For now, exact version needs to be specified.
- Updated cullenect geometry for the v2.0.3 beta, horizontal ribs.

### CODE REVIEW

**Comment by ndevenish** [comment]
@CullenJWebb I think this is now matching your 2.0.3-beta geometry. The text emboss depth on top doesn't match (is 0.4mm instead of 0.2mm) but at the moment this is configured by argument directly (and not split per-base). I can make it change the text depth by default if you think it is important.

Generating labels with this branch and the new shape:
```
gflabel cullenect --version=v2.0.3-beta "Label Text"
```

**Comment by CullenJWebb** [comment]
This looks excellent. I'm going to do some testing with this.

**Comment by ostat** [comment]
What do you guys think about supporting changing x (and maybe y) dimensions for both version 1 and version 2 of **cullenect** ?

The default size for version 1 is 36.4mm with a hole space of 36.7, however if you have a 1 unit length Gridfinity bin with the standard lip you only have 36.3 mm. Which sounds ok, but its too tight. Also someone might want a label for a less than ro greater than 1 unit bin.

I would like to support changing the size of the label in the lip.

For reference.
https://github.com/ostat/gridfinity_extended_openscad/issues/53

**Comment by ndevenish** [comment]
It looks like the issue there is specifically that the gridfinity_extended_openscad changed geometry such that the standard labels don't fit any more?

I'm open to adding the ability to tune the base sizes, as long as the "standard" size is the default. I think it'd be pretty simple to support changing the basic sizes with overrides. It would be easiest just to assume that the click-bars stay in the same relative size/position and the label ends up being whatever custom size on top of that. Does that sound like it would help?

**Comment by ndevenish** [comment]
> I think keeping the bars in the same position makes sense. Could we keep the pattern going, so after the first bar, a bar is every _n_mm following the current pattern?

Like, span all the way to where the next bin would be? I've thought it would be useful to be able to have a multibin-length label, but was reluctant to invent my own modification of what was supposed to be a standard. Could always have it as advanced options, I guess.

**Comment by ndevenish** [comment]
Okay, so it looks like the final v2 didn't have this orientation change at all, so I'll close this to separately add the real v2 update.

**Pull request closed without merging**
